name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Zip artifact
        run: Compress-Archive -Path ./publish/WU-Tamer.exe -DestinationPath ./WU-Tamer-${{ github.ref_name }}-win-x64.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: WU-Tamer-${{ github.ref_name }}-win-x64.zip
